name: lost_and_found_map_app
description: "A Lost and Found Map App using Flutter"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.1.8
  permission_handler: ^10.0.0+2
  google_maps_webservice: 0.0.20-nullsafety.5
  geolocator: ^9.0.2
  intl: ^0.17.0
  flutter_google_places: ^0.3.0
  sqflite: ^2.0.0+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

assets:
  - assets/marker.png
